baseURL: https://mlane-portfolio.netlify.app
languageCode: en-us
title: Matthew Lane Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      My portfolio website released under the creative commons
    
    title: Hi, my name is Matthew Lane. This is my portfolio website!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        postcode: NW1 4SA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mlane.mfa2022@london.edu 
        title: Email
    enable: no
    phone:
      - phone: 07714472280
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Matthew Lane
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/matthew.lane.7355
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/matthewtlane/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/matthewtlane
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: IMG_2642.jpg.
        subtitle: Select to view current CV
        title: CV
        url: blogs/CV
      - image: pic02.jpg
        subtitle: Click to view my Machine Learning for Economics project
        title: Machine Learning
        url: blogs/tempus
      - image: pic99.jpg
        subtitle: Rmd file calculating Risk-Return trade for DJIA stocks
        title: Risk Return Analysis
        url: content/blogs/blog1.md
      - image: pic06.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
#      - image: pic06.jpg
#       subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
