baseURL: https://mlane-portfolio.netlify.app
languageCode: en-us
title: Matthew Lane Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I'm currently a Masters in Financial Analysis student at London Business School looking for graduate roles in Investment Banking or Private Equity/Growth Capital
    title: Hi, my name is Matthew Lane and this is my portfolio website!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        postcode: NW1 4SA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mlane.mfa2022@london.edu 
        title: Email
    enable: no
    phone:
      - phone: 07714472280
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Matthew Lane
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/matthew.lane.7355
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/matthewtlane/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/matthewtlane
  image: ''
  name: Matthew Lane
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: IMG_2642.jpg
        subtitle: Select to view my current CV
        title: CV
        url: blogs/Matthew_Lane_CV_2021
      - image: pic02.jpg
        subtitle: Code for my undergraduate Machine Learning project predicting house prices in Taiwan. 
        title: Machine Learning
        url: blogs/house_price_prediction
      - image: pic99.jpg
        subtitle: Rmd file calculating Risk-Return trade for DJIA stocks
        title: Risk Return Analysis
        url: blogs/risk_return
      - image: picCfL.jpg
        subtitle: Click to view markdown file of my first group project for Data Analytics for Finance
        title: Group Project 1
        url: blogs/group_project_1
      - image: picCW.jpg
        subtitle: Click to view markdown file of my second group project for Data Analytics for Finance
        title: Group Project 2
        url: blogs/group_project_2
      - image: picW.jpg
        subtitle: Click to view markdown file of my third group project for Data Analytics for Finance
        title: Group Project 3
        url: blogs/group_project_3
#  two:
#    buttonText: Get Started
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#    title: Massa libero
#    url: blogs
